### ISSUE TITLE
Remove newline before success message

### ISSUE THREAD

**Issue by yargalot** [yargalot/AccessSniff#15]
ref @XhmikosR via https://github.com/yargalot/grunt-accessibility/issues/31#issuecomment-186790412

**Comment by XhmikosR** [comment]
@yargalot: I don't think this is AccessSniff related only. I mean, you'll need to use `grunt.log.ok` too in the grunt plugin for the success message and `grunt.fail.warn` in case it fails.

**Comment by yargalot** [comment]
Done in 3.0
