### ISSUE TITLE
Update (dev)dependencies and npm shrinkwrap

### ISSUE THREAD

**Issue by XhmikosR** [yargalot/AccessSniff#16]
Mostly to keep the dependency tree as clean as possible :)

**Comment by bshack** [comment]
having some problems with github:squizlabs/HTML_CodeSniffer#2.0.6 and npm shrinkwrap. Appears to be some issues with dependencies defined in that specific version. Looks like it has a mix of versions for this project defined, 2.0.1 and 2.0.6. See this issue:

https://github.com/squizlabs/HTML_CodeSniffer/issues/154

Causes me to have to go in and manually swap out the 2.0.6 dependency in accesssniff with the 2.0.1 version to allow my project to be shrinkwrapped.

**Comment by yargalot** [comment]
Looks like they are not changing the package.json version on new releases. 😬

Would it fix your issue If i removed the shrinkwrap in this project @bshack?

**Comment by bshack** [comment]
i think if you pulled in 2.0.1 explicitly that would do it, but would have to test it. Wouldn't want you to have to drop shrinkwrap on your project. Maybe other project will fix sooner than later.

**Comment by yargalot** [comment]
What if I fork it, update the version in the pacage.json and tag a new release and have this project refer to the fork.

Can put in a request as part of squizlabs/HTML_CodeSniffer#154, but they are pretty slow on responses tbh.

**Comment by bshack** [comment]
that works thanks! Let me know and I will test it on my end.

**Comment by yargalot** [comment]
Will sort this out tonight @bshack. 

HTML_Codesniffer is such a black box of unknowns, might need to consider making my own client side lib.

**Comment by bshack** [comment]
cool let me know when you want to verify it on my end

**Comment by yargalot** [comment]
Hang on I think he has released from the 2.0 branch

**Comment by XhmikosR** [comment]
@yargalot: 

```
C:\Users\xmr\Desktop\AccessSniff>ncu

 axios         ^0.8.1  →  ^0.9.1
 bluebird     ^2.9.13  →  ^3.3.1
 validator    ^3.39.0  →  ^5.0.0
 gulp-eslint   ^1.1.1  →  ^2.0.0

Run with -u to upgrade package.json
```

**Comment by yargalot** [comment]
hok

**Comment by XhmikosR** [comment]
The bluebird one might be breaking IIRC.

**Comment by yargalot** [comment]
Yeh new vesion of bluebird breaks the build

**Comment by XhmikosR** [comment]
I tried to do this myself the other day, but couldn't figure out which API changed :/

**Comment by yargalot** [comment]
Hok it was using an old version of promise stuff, thats updated at https://github.com/yargalot/AccessSniff/commit/1220cf77ea81bc8dab898a3c35d597142ba7c416

@bshack Give v2.4.0 a crack and see if fixes your issue 🎉

**Comment by bshack** [comment]
nice. fixed it for me!

**Comment by yargalot** [comment]
Huzzah! Will close this one off then 😺
