### ISSUE TITLE
Allow for external URL targets

### ISSUE THREAD

**Issue by andrewholgate** [yargalot/AccessSniff#2]
Firstly, thank you for this great integration of HTML_CodeSniffer.

In additional to local files, it would be very useful if AccessSniff could also target URL's (as HTML_CodeSniffer allows).

This way, accessibility tests could be run on dynamically generated content in development and staging as well as allowing for external tests on a production server, using the current version of the live content.

**Comment by yargalot** [comment]
Good idea, will throw it in next release

**Comment by andrewholgate** [comment]
Thanks!

**Comment by yargalot** [comment]
No probs man, let me know if you find anything else. Glad its helping out!
