### ISSUE TITLE
Please bump npm package version.  

### ISSUE THREAD

**Issue by chalettu** [yargalot/AccessSniff#24]
Hi,
   I was trying to use this for Section508 support but the changes are in master and the version of the package hasn't been bumped to include those changes.  Can you bump the package version to 2.4.5 ?  Thanks in advance

**Comment by yargalot** [comment]
Hey @chalettu, Just did that then. 2.4.5 is up on NPM. 

Sorry about not publishing it, totally forgot

**Comment by yargalot** [comment]
closes #22

**Comment by yargalot** [comment]
closes #21

**Comment by yargalot** [comment]
@chalettu Let me know if there are any issues

**Comment by chalettu** [comment]
Thank you so much @yargalot .  I really appreciate it!
