### ISSUE TITLE
Test pages behind login

### ISSUE THREAD

**Issue by lukasoppermann** [yargalot/AccessSniff#26]
Hey,

is there any way I could use this to test pages behind a login form?

**Comment by yargalot** [comment]
So the base is phantomJs, so I could allow you to pass options / cookies / localstorage to it if thats whats needed?

**Comment by lukasoppermann** [comment]
Something like this would be nice. I actually did not really investigate how best to do it, as it is a php application and I would also need to gather all routes to test them. But I guess since it is probably with secure only cookies that need to be created by the server it would not work, right?

I would probably need to have a test version without the login.
