### ISSUE TITLE
accessibilityLevel option not being passed on to HTML_CodeSniffer.

### ISSUE THREAD

**Issue by andrewholgate** [yargalot/AccessSniff#3]
I discovered this issue when using [grunt-accessibility](https://github.com/yargalot/grunt-accessibility) but it appears to originate from this module.

Basically, when I configure the Gruntfile to:

```
accessibility: {
  options: {
    accessibilityLevel: "WCAG2AAA"
  }
}
```

The output from the accessibility review is based on `WCAG2A` and not `WCAG2AAA`.

I'm not very familar with this code base but the options seems to be reset on [this line of  AccessSniff](https://github.com/yargalot/AccessSniff/blob/master/src/phantom.js#L10)

**Comment by yargalot** [comment]
Must've forgot to take that one out when I was testing it. Will remove that one

**Comment by yargalot** [comment]
Should all be working now :)

**Comment by andrewholgate** [comment]
Nice work, I can confirm that this patch fixes the issue. Thanks mate.
