### ISSUE TITLE
Update HTML_CodeSniffer

### ISSUE THREAD

**Issue by XhmikosR** [yargalot/AccessSniff#35]
https://github.com/squizlabs/HTML_CodeSniffer/releases/tag/2.1.0

**Comment by XhmikosR** [comment]
@yargalot: ping

**Comment by yargalot** [comment]
Ah yeh forgot about this, will make time to fix the issues in this repo this weekend.

**Comment by yargalot** [comment]
right, Just going through this all, this is going to be a bit more than just updated number. Will keep going

**Comment by XhmikosR** [comment]
Any news about this @yargalot?

**Comment by prantlf** [comment]
Fixed by #44, upgrade to 2.1.1.

**Comment by yargalot** [comment]
Updated in release 3.2.0  👍
