### ISSUE TITLE
Pull HTML_CodeSniffer from NPM

### ISSUE THREAD

**Issue by AntoniBertel** [yargalot/AccessSniff#40]
Hi,

Most organisations are mirroring public repositories can't use AccessSniff and libraries dependent from AccessSniff due to security and licence limitations. 
(Because of direct pull of dependencies from Githubis blocked)

HTML_CodeSniffer just released in NPM, https://www.npmjs.com/package/html_codesniffer
Could you please use NPM dependency instead of Github?
`"HTML_CodeSniffer": "squizlabs/HTML_CodeSniffer#2.0.7"`
Thank you.

**Comment by prantlf** [comment]
Fixed by #44, including the upgrade to 2.1.1.

**Comment by yargalot** [comment]
fixed in 3.2.0 release
