### ISSUE TITLE
Where do you set the options?

### ISSUE THREAD

**Issue by martinwrightinfo** [yargalot/AccessSniff#5]
I want to set the options to only output WCAG2AA errors using the CLI. But I didn't understand from your documentation which file I set these? 

```
options: {
    accessibilityLevel: 'WCAG2A'
  }
```

```
options: {
    reportLevels: {
      notice: true,
      warning: true,
      error: true
    }
  }
```
Kind Regards, Martin

**Comment by yargalot** [comment]
Hey mate, the options get set through the command line, so it would be `sniff test/**/*.html -r json -l reports`, it wont refer to a file unless you have a .accessibilityrc file (I think, it should pick it up automatically depending on if you run it from the same folder)

I could make an option for the cli to reference a file directly if you pass the flag, something like `sniff test/**/*.html -optionFile .accessibilityrc` or something like that?

**Comment by themightywrighty** [comment]
I couldn't get it to pick up and my .accessibilityrc no matter where I put it. 

What I did in the end was to install the access-sniff package locally then create a javascript file called  wcag-test.js so I could set the options there. I then ran `nodejs wcag-test.js` to do my test. That seem to work quite well. 

```
var accessSniff = require('access-sniff');
var files = [

  'http://www.exampleurl.com/page1.html',
  'http://www.exampleurl.com/page2.html'
            ];
var options = { accessibilityLevel: 'WCAG2AA', reportType: 'json', reportLevels: {
  notice: false,
  warning: false,
  error: true
} };

accessSniff.start(files, options);
```
