### ISSUE TITLE
Add option to pipe the results to a report

### ISSUE THREAD

**Issue by TheDutchCoder** [yargalot/AccessSniff#6]
Right now the plugin lets you either log the results to the console, or it generates individual reports.
But in gulp it's common to pipe the result to a destination.

I'd rather have control over the stream and pipe everything to one file (or multiple files as an option), as I'm doing multiple audits and generate individual reports for each audit.

Would be great to have!

**Comment by rhewitt22** [comment]
+1 

I'm having a problem where the output continually overwrites `/reports/index.json`.  It'd be great if I could have more control over the output reports.

**Comment by yargalot** [comment]
Finished with release 2.2.0 https://github.com/yargalot/AccessSniff/commit/107aba796251f800e9b3b198a3ec27539633a647
