### ISSUE TITLE
Raw String Input

### ISSUE THREAD

**Issue by adamclerk** [yargalot/AccessSniff#7]
Would you entertain a PR that allowed a user to pass in an HTML string in addition to url and file?

**Comment by yargalot** [comment]
Hi @adamclerk,

Sounds like a good idea, Would totally accept it. 

Only thing is Im currently rewriting the library, so if you can pull it against the develop branch (https://github.com/yargalot/AccessSniff/tree/develop) then that would be great!

**Comment by yargalot** [comment]
Le merged
